// web/app/pages/login/index.vue
<script setup lang="ts">
import type { SignInOptions } from '~/types/auth';

/** Sign in with a password, a passkey, single sign-on or a social provider. */
const { t } = useT();
const route = useRoute();
const { data: options } = await useApi<SignInOptions>('/auth/options');
</script>

<template>
    <AuthFrame
        :heading="t('Sign in')"
        :description="t('One account for Deploy, Monitoring, Analytics and everything else on :app.', { app: 'BuildPusher' })"
        :status="options.status"
    >
        <div v-if="options.error" class="ui-alert ui-alert--danger ui-alert-danger mb-5" role="alert">{{ options.error }}</div>
        <div class="grid gap-5">
            <SignInForm :redirect="safeRedirect(route.query.redirect)" />
            <SocialProviders :providers="options.socialProviders" />
        </div>
        <template #footer>
            {{ t('New here?') }} <NuxtLink to="/register" class="font-bold text-primary underline">{{ t('Create an account') }}</NuxtLink>
        </template>
    </AuthFrame>
</template>

// web/app/(auth)/login/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { AuthFrame } from '@/components/auth/AuthFrame';
import { SignInForm } from '@/components/auth/SignInForm';
import { SocialProviders } from '@/components/auth/SocialProviders';
import { safeRedirect, signInOptions } from '@/lib/auth';
import { t } from '@/lib/i18n';
import { guestTranslator } from '@/lib/locale';

export const metadata: Metadata = { title: 'Sign in' };

/** Sign in with a password, a passkey, single sign-on or a social provider. */
export default async function SignInPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
    const query = await searchParams;
    const [i18n, options] = await Promise.all([guestTranslator(), signInOptions()]);

    return (
        <AuthFrame
            i18n={i18n}
            heading={t(i18n, 'Sign in')}
            description={t(i18n, 'One account for Deploy, Monitoring, Analytics and everything else on :app.', { app: 'BuildPusher' })}
            status={options.status}
            footer={<>{t(i18n, 'New here?')} <Link href="/register" className="font-bold text-primary underline">{t(i18n, 'Create an account')}</Link></>}
        >
            {options.error && <div className="ui-alert ui-alert--danger ui-alert-danger mb-5" role="alert">{options.error}</div>}
            <div className="grid gap-5">
                <SignInForm redirect={safeRedirect(query.redirect)} />
                <SocialProviders providers={options.socialProviders} />
            </div>
        </AuthFrame>
    );
}
