// web/app/components/shell/Toaster.vue
<script setup lang="ts">
/**
 * Shows the message an action left (after a navigation, or on the same page after a save), announced to screen
 * readers, for a few seconds.
 */
const { t } = useT();
const route = useRoute();
const toast = ref<{ message: string; tone: string } | null>(null);
let timer: number | undefined;

/** Show the waiting message, if there is one. */
function present() {
    const next = takeFlash();
    if (next) {
        toast.value = next;
        window.clearTimeout(timer);
        timer = window.setTimeout(() => (toast.value = null), 6000);
    }
}

onMounted(() => {
    window.addEventListener(EVENT, present);
    // A message carried across a full page load is waiting when the page appears.
    present();
});
onBeforeUnmount(() => window.removeEventListener(EVENT, present));
// …and one carried across a navigation inside the app, once the new page is there.
watch(() => route.path, () => nextTick(present));
</script>

<template>
    <div class="pointer-events-none fixed inset-x-0 bottom-4 z-50 flex justify-center px-4" aria-live="polite" role="status">
        <div v-if="toast" :class="['ui-alert pointer-events-auto flex max-w-lg items-start gap-3 shadow-panel', `ui-alert--${toast.tone}`, `ui-alert-${toast.tone}`]">
            <span class="text-sm">{{ toast.message }}</span>
            <button type="button" class="ui-icon-btn ui-icon-btn-sm -my-1 -mr-1 shrink-0" :aria-label="t('Dismiss')" @click="toast = null">
                <Icon name="close" class="h-4 w-4" />
            </button>
        </div>
    </div>
</template>

// web/components/shell/Toaster.tsx
'use client';

import { usePathname } from 'next/navigation';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Icon } from '@/components/signal/Icon';
import { EVENT, takeFlash } from '@/lib/flash';
import { useT } from '@/lib/i18n-client';

type Toast = { message: string; tone: string };

/**
 * Shows the message an action left (after a navigation, or on the same page after a save), announced to screen
 * readers, for a few seconds.
 */
export function Toaster() {
    const { t } = useT();
    const pathname = usePathname();
    const [toast, setToast] = useState<Toast | null>(null);
    const timer = useRef<number | undefined>(undefined);

    const present = useCallback(() => {
        const next = takeFlash();
        if (next) {
            setToast(next);
            window.clearTimeout(timer.current);
            timer.current = window.setTimeout(() => setToast(null), 6000);
        }
    }, []);

    // A message for this page (a save that refreshed it) arrives as an event.
    useEffect(() => {
        window.addEventListener(EVENT, present);
        return () => window.removeEventListener(EVENT, present);
    }, [present]);

    // A message carried across a navigation is waiting when the new page appears.
    useEffect(() => {
        const frame = window.requestAnimationFrame(present);
        return () => window.cancelAnimationFrame(frame);
    }, [pathname, present]);

    return (
        <div className="pointer-events-none fixed inset-x-0 bottom-4 z-50 flex justify-center px-4" aria-live="polite" role="status">
            {toast && (
                <div className={`ui-alert ui-alert--${toast.tone} ui-alert-${toast.tone} pointer-events-auto flex max-w-lg items-start gap-3 shadow-panel`}>
                    <span className="text-sm">{toast.message}</span>
                    <button type="button" className="ui-icon-btn ui-icon-btn-sm -my-1 -mr-1 shrink-0" aria-label={t('Dismiss')} onClick={() => setToast(null)}>
                        <Icon name="close" className="h-4 w-4" />
                    </button>
                </div>
            )}
        </div>
    );
}
