// web/app/pages/projects/[project]/audit/index.vue
<script setup lang="ts">
import type { AuditListItem, AuditPlan, Goal } from '~/types/audit';

/** The project's audits: each site with its latest score, how much of the month is used, and setting one up (a wizard). */
definePageMeta({ layout: 'app', service: 'audit' });
const { t, tc, dateTime } = useT();
const route = useRoute();
const { data } = await useApi<{ audits: AuditListItem[]; plan: AuditPlan; goals: Goal[] }>(() => `/projects/${route.params.project}/audit`);
const projectId = computed(() => String(route.params.project));
const canAdd = computed(() => data.value.plan.canManage && (data.value.plan.auditLimit === null || data.value.audits.length < data.value.plan.auditLimit));
useHead({ title: () => t('Audits') });
</script>

<template>
    <div class="space-y-6">
        <PageHeader icon="search" eyebrow="Audit" :title="t('Audits')" :description="t('Watch a visitor use your site and your competitors’, and see what to improve.')">
            <template v-if="canAdd" #actions>
                <UiButton variant="primary" :to="{ query: { dialog: 'new-audit' } }"><Icon name="plus" class="h-4 w-4" />{{ t('New audit') }}</UiButton>
            </template>
        </PageHeader>
        <p class="text-xs font-semibold text-muted">
            {{ data.plan.runsAllowance === null ? tc(':count audit run this month|:count audits run this month', data.plan.runsUsed, { count: data.plan.runsUsed }) : t(':used of :allowance audits used this month', { used: data.plan.runsUsed, allowance: data.plan.runsAllowance }) }}
            <template v-if="data.plan.tier"> · {{ t(':tier plan', { tier: data.plan.tier }) }}</template>
        </p>

        <EmptyState v-if="data.audits.length === 0" icon="search" :title="t('No audits yet')" :description="t('Add your site and a few competitors. A visitor tries real tasks on each, and the report shows what to improve first.')">
            <template #action><UiButton v-if="data.plan.canManage" variant="primary" :to="{ query: { dialog: 'new-audit' } }">{{ t('Set up your first audit') }}</UiButton></template>
        </EmptyState>
        <ul v-else class="grid gap-3 md:grid-cols-2">
            <li v-for="audit in data.audits" :key="audit.id">
                <NuxtLink :to="`/projects/${projectId}/audit/${audit.id}`" class="ui-card ui-card--interactive flex h-full flex-col gap-4 p-5">
                    <div class="flex items-start justify-between gap-3">
                        <div class="min-w-0">
                            <h2 class="truncate text-base font-extrabold text-ink">{{ audit.name }}</h2>
                            <p class="truncate text-sm text-muted">{{ audit.url }}</p>
                        </div>
                        <RunBadge v-if="audit.latestRun" :run="audit.latestRun" />
                    </div>
                    <p class="mt-auto flex flex-wrap gap-x-4 gap-y-1 text-xs font-semibold text-muted">
                        <span>{{ tc(':count competitor|:count competitors', audit.competitors, { count: audit.competitors }) }}</span>
                        <span>{{ audit.latestRun ? t('Last run :date', { date: dateTime(audit.latestRun.createdAt) }) : t('Not run yet') }}</span>
                    </p>
                </NuxtLink>
            </li>
        </ul>

        <UiDialog v-if="canAdd" id="new-audit" :title="t('New audit')" size="wide">
            <template #default="{ close }"><AuditWizard :project-id="projectId" :plan="data.plan" :goals="data.goals" @done="close" /></template>
        </UiDialog>
    </div>
</template>

// web/app/projects/[project]/audit/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { RunBadge } from '@/components/audit/RunBadge';
import { ButtonLink } from '@/components/signal/Button';
import { EmptyState } from '@/components/signal/EmptyState';
import { Icon } from '@/components/signal/Icon';
import { PageHeader } from '@/components/signal/PageHeader';
import { api } from '@/lib/api';
import { projectContext } from '@/lib/context';
import { dateTime, t, tc } from '@/lib/i18n';
import type { AuditListItem, AuditPlan, Goal } from '@/lib/types';

export const metadata: Metadata = { title: 'Audit' };

/** The project's audits: each site with its latest score, and how much of the month's allowance is used. */
export default async function AuditsPage({ params }: { params: Promise<{ project: string }> }) {
    const { project } = await params;
    const [{ i18n }, data] = await Promise.all([
        projectContext(project, 'audit'),
        api<{ audits: AuditListItem[]; plan: AuditPlan; goals: Goal[] }>(`/projects/${project}/audit`),
    ]);
    const base = `/projects/${project}/audit`;
    const canAdd = data.plan.canManage && (data.plan.auditLimit === null || data.audits.length < data.plan.auditLimit);

    return (
        <>
            <PageHeader
                i18n={i18n}
                icon="search"
                eyebrow="Audit"
                title={t(i18n, 'Audits')}
                description={t(i18n, 'Watch a visitor use your site and your competitors’, and see what to improve.')}
                actions={canAdd ? <ButtonLink href={`${base}/new`} variant="primary" scroll={false}><Icon name="plus" className="h-4 w-4" />{t(i18n, 'New audit')}</ButtonLink> : undefined}
                metadata={
                    <span className="text-xs font-semibold text-muted">
                        {data.plan.runsAllowance === null
                            ? tc(i18n, ':count audit run this month|:count audits run this month', data.plan.runsUsed)
                            : t(i18n, ':used of :allowance audits used this month', { used: data.plan.runsUsed, allowance: data.plan.runsAllowance })}
                        {data.plan.tier && ` · ${t(i18n, ':tier plan', { tier: data.plan.tier })}`}
                    </span>
                }
            />

            {data.audits.length === 0 ? (
                <EmptyState
                    icon="search"
                    title={t(i18n, 'No audits yet')}
                    description={t(i18n, 'Add your site and a few competitors. A visitor tries real tasks on each, and the report shows what to improve first.')}
                    action={data.plan.canManage ? <ButtonLink href={`${base}/new`} variant="primary" scroll={false}>{t(i18n, 'Set up your first audit')}</ButtonLink> : undefined}
                />
            ) : (
                <ul className="grid gap-3 md:grid-cols-2">
                    {data.audits.map((audit) => (
                        <li key={audit.id}>
                            <Link href={`${base}/${audit.id}`} className="ui-card ui-card--interactive flex h-full flex-col gap-4 p-5">
                                <div className="flex items-start justify-between gap-3">
                                    <div className="min-w-0">
                                        <h2 className="truncate text-base font-extrabold text-ink">{audit.name}</h2>
                                        <p className="truncate text-sm text-muted">{audit.url}</p>
                                    </div>
                                    {audit.latestRun && <RunBadge i18n={i18n} run={audit.latestRun} />}
                                </div>
                                <p className="mt-auto flex flex-wrap gap-x-4 gap-y-1 text-xs font-semibold text-muted">
                                    <span>{tc(i18n, ':count competitor|:count competitors', audit.competitors)}</span>
                                    <span>{audit.latestRun ? t(i18n, 'Last run :date', { date: dateTime(i18n, audit.latestRun.createdAt) }) : t(i18n, 'Not run yet')}</span>
                                </p>
                            </Link>
                        </li>
                    ))}
                </ul>
            )}
        </>
    );
}
