// web/app/components/audit/RunBadge.vue
<script setup lang="ts">
import type { RunSummary } from '~/types/audit';

/** A run's state, or its score once done, with words as well as colour. */
const props = defineProps<{ run: RunSummary }>();
const { t } = useT();
const badge = computed(() => {
    if (props.run.status === 'done' && props.run.score !== null) {
        return { tone: scoreTone(props.run.score), label: t('Score :score', { score: props.run.score }) };
    }
    return {
        queued: { tone: 'neutral' as const, label: t('Waiting to start') },
        running: { tone: 'info' as const, label: t('Running') },
        done: { tone: 'success' as const, label: t('Done') },
        failed: { tone: 'danger' as const, label: t('Failed') },
    }[props.run.status];
});
</script>

<template>
    <Badge :tone="badge.tone">{{ badge.label }}</Badge>
</template>

// web/components/audit/RunBadge.tsx
import { Badge, type Tone } from '@/components/signal/Badge';
import { t, type Translator } from '@/lib/i18n';
import type { RunSummary } from '@/lib/types';

/** A run's state, or its score once done, with words as well as colour. */
export function RunBadge({ i18n, run }: { i18n: Translator; run: RunSummary }) {
    if (run.status === 'done' && run.score !== null) {
        return <Badge tone={scoreTone(run.score)}>{t(i18n, 'Score :score', { score: run.score })}</Badge>;
    }
    const states: Record<RunSummary['status'], [string, Tone]> = {
        queued: [t(i18n, 'Waiting to start'), 'neutral'],
        running: [t(i18n, 'Running'), 'info'],
        done: [t(i18n, 'Done'), 'success'],
        failed: [t(i18n, 'Failed'), 'danger'],
    };
    const [label, tone] = states[run.status];

    return <Badge tone={tone}>{label}</Badge>;
}

/** The tone for a 0–100 score: good from 80, fair from 50. */
export function scoreTone(score: number): Tone {
    return score >= 80 ? 'success' : score >= 50 ? 'warning' : 'danger';
}
